travis configuration + pep8 fixes
Summary:* added `.travis.yml` file
* found out that flake8 could be configured via `setup.cfg`. So I added:

```
$ cat ~/.config/flake8.BK
[flake8]
max-line-length = 80
```

However `python3 setup.py flake8` fails with:

```
File "/.../.eggs/pep8-1.5.7-py3.4.egg/pep8.py", line 204, in maximum_line_length
if length > max_line_length and not noqa(line):
TypeError: unorderable types: int() > str()
```

There is a bug in pep8 when picking config from setup.cfg.
It's faster for now to comply with 79 chars columns so that's what the rest
of the diff is about :)

Reviewed By: insomniacslk

Differential Revision: D3016284

fb-gh-sync-id: 820019ed216f9db6c18a5d1015222006337b6b42
shipit-source-id: 820019ed216f9db6c18a5d1015222006337b6b42